/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ObexAgentAdaptop -p obexagentadaptor obexagent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OBEXAGENTADAPTOP_H_1436821351
#define OBEXAGENTADAPTOP_H_1436821351

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.openobex.Agent
 */
class AgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.openobex.Agent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.openobex.Agent\">\n"
"    <method name=\"Authorize\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg type=\"o\" name=\"transfer\"/>\n"
"      <arg type=\"s\" name=\"bt_address\"/>\n"
"      <arg type=\"s\" name=\"name\"/>\n"
"      <arg type=\"s\" name=\"type\"/>\n"
"      <arg type=\"i\" name=\"length\"/>\n"
"      <arg type=\"i\" name=\"time\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"Cancel\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AgentAdaptor(QObject *parent);
    virtual ~AgentAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString Authorize(const QDBusObjectPath &transfer, const QString &bt_address, const QString &name, const QString &type, int length, int time);
    void Cancel();
Q_SIGNALS: // SIGNALS
};

#endif
