/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ObexAgentAdaptor -a obexagentadaptor obexagent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OBEXAGENTADAPTOR_H_1437077107
#define OBEXAGENTADAPTOR_H_1437077107

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.openobex.Agent
 */
class ObexAgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.openobex.Agent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.openobex.Agent\">\n"
"    <method name=\"Release\"/>\n"
"    <method name=\"Request\">\n"
"      <arg type=\"o\" name=\"transfer\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"Progress\">\n"
"      <arg type=\"o\" name=\"transfer\"/>\n"
"      <arg type=\"i\" name=\"transferred\"/>\n"
"    </method>\n"
"    <method name=\"Complete\">\n"
"      <arg type=\"o\" name=\"transfer\"/>\n"
"    </method>\n"
"    <method name=\"Error\">\n"
"      <arg type=\"o\" name=\"transfer\"/>\n"
"      <arg type=\"s\" name=\"message\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ObexAgentAdaptor(QObject *parent);
    virtual ~ObexAgentAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Complete(const QDBusObjectPath &transfer);
    void Error(const QDBusObjectPath &transfer, const QString &message);
    void Progress(const QDBusObjectPath &transfer, int transferred);
    void Release();
    QString Request(const QDBusObjectPath &transfer);
Q_SIGNALS: // SIGNALS
};

#endif
