/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ObexAgentAdaptor -a obexagentadaptor obexagent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "obexagentadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ObexAgentAdaptor
 */

ObexAgentAdaptor::ObexAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ObexAgentAdaptor::~ObexAgentAdaptor()
{
    // destructor
}

QString ObexAgentAdaptor::AuthorizePush(const QDBusObjectPath &transfer)
{
    // handle method call org.bluez.obex.Agent1.AuthorizePush
    QString path;
    QMetaObject::invokeMethod(parent(), "AuthorizePush", Q_RETURN_ARG(QString, path), Q_ARG(QDBusObjectPath, transfer));
    return path;
}

void ObexAgentAdaptor::Cancel()
{
    // handle method call org.bluez.obex.Agent1.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void ObexAgentAdaptor::Release()
{
    // handle method call org.bluez.obex.Agent1.Release
    QMetaObject::invokeMethod(parent(), "Release");
}
